apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /openshift-ingress-router
  name: openshift-ingress-router
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|openshift-ingress-router'
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /openshift-ingress-router
  name: openshift-ingress-router
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|openshift-ingress-router'
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: openshift-ingress-router
subjects:
- kind: ServiceAccount
  namespace: openshift-ingress
  name: ingress-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /openshift-ingress-router-auth-delegator
  name: openshift-ingress-router-auth-delegator
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|openshift-ingress-router-auth-delegator'
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  namespace: openshift-ingress
  name: ingress-router
---
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /openshift-ingress
  name: openshift-ingress
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|openshift-ingress'
---
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: openshift-ingress/ingress-router
  name: ingress-router
  namespace: openshift-ingress
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|openshift-ingress|ingress-router'
